"""empty message

Revision ID: 2a38643096c0
Revises: 52d9439c12c2
Create Date: 2014-11-23 09:07:47.590000

"""

# revision identifiers, used by Alembic.
revision = '2a38643096c0'
down_revision = '52d9439c12c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('locations', sa.Column('published', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'published')
    op.drop_column('locations', 'deleted')
    ### end Alembic commands ###
